environment:
  PYTHON_HOME: "C:\\Python37"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Debug
      CONAN_VISUAL_RUNTIMES: MTd
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Debug
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Debug
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 2
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MT
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 2
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Debug
      CONAN_VISUAL_RUNTIMES: MTd
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Debug
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Debug
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 2
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MT
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 2
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_BUILD_TYPES: Debug
      CONAN_VISUAL_RUNTIMES: MTd
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_BUILD_TYPES: Debug
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_BUILD_TYPES: Debug
      CONAN_VISUAL_RUNTIMES: MDd
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 2
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MT
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_BUILD_TYPES: Release
      CONAN_VISUAL_RUNTIMES: MD
      CONAN_TOTAL_PAGES: 2
      CONAN_CURRENT_PAGE: 2

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip install bincrafters_package_tools
  - conan user # It creates the conan data directory

build_script:
  - python build.py
